language: node_js

os:
  - linux
  
  
jobs:
  include:
    - name: 'Automated API tests using Postman CLI'
      os: linux
      node_js: '14'
      script:
        - curl https://dl-cli.pstmn-beta.io/download/latest/linux/ -o postman-cli.tar.gz
        - sudo tar -zxvf postman-cli.tar.gz
        - mkdir -p /usr/local/bin/
        - sudo mv postman-cli /usr/local/bin/postman
        - rm postman-cli.tar.gz
        - export POSTMAN_API_BASE_URL='https://api.getpostman-beta.com'
        - postman login --with-api-key $POSTMAN_API_KEY
        - postman collection run 868404-037c0b78-de02-4c29-9e6d-79a7982a50a2
